# Nome da aplicacao
spring.application.name=dsmovie

# Perfil ativo (test, dev ou prod)
spring.profiles.active=${APP_PROFILE:dev}

# Configuracoes globais
spring.jpa.open-in-view=false

server.port=${PORT:8080}