spring.application.name=dsmovie

# Desativa o padrão 'Open Session In View' para evitar consultas ao banco 
# durante a renderização da resposta, melhorando a performance e o controle.
#spring.jpa.open-in-view=false

# Define credenciais estáticas para o Spring Security, evitando que uma 
# senha aleatória seja gerada no console a cada inicialização.
#spring.security.user.name=admin
#spring.security.user.password=12345
