INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_movie(score, count, title, image) VALUES (4.5, 2, 'The Witcher', '/img/dsmovie-The_Witcher.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (3.3, 3, 'Venom: Tempo de Carnificina', '/img/dsmovie-Venom-Tempo_de_Carnificina.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Espetacular Homem-Aranha 2: A Ameaça de Electro', '/img/dsmovie-O_Espetacular_Homem-Aranha_2-_A_Ameaca_de_Electro.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Matrix Resurrections', '/img/dsmovie-Matrix_Resurrections.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Shang-Chi e a Lenda dos Dez Anéis', '/img/dsmovie-Shang-Chi_e_a_Lenda_dos_Dez_Aneis.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Django Livre', '/img/dsmovie-Django_Livre.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Titanic', '/img/dsmovie-Titanic.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Lobo de Wall Street', '/img/dsmovie-O_Lobo_de_Wall_Street.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Aves de Rapina: Arlequina e sua Emancipação Fantabulosa', '/img/dsmovie-Aves_de_Rapina_Arlequina_e_sua_Emancipacao_Fantabulosa.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Rogue One: Uma História Star Wars', '/img/dsmovie-Rogue_One_Uma_Historia_Star_Wars.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Star Wars: A Guerra dos Clones', '/img/dsmovie-Star_Wars_A_Guerra_dos_Clones.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Star Wars: Episódio I - A Ameaça Fantasma', '/img/dsmovie-Star_Wars-Episodio_I-_A_Ameaca_Fantasma.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Vingadores: Ultimato', '/img/dsmovie-Vingadores_Ultimato.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Thor', '/img/dsmovie-Thor.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Cisne Negro', '/img/dsmovie-Cisne_Negro.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Silêncio dos Inocentes', '/img/dsmovie-O_Silencio_dos_Inocentes.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Clube da Luta', '/img/dsmovie-Clube_da_Luta.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Guerra Mundial Z', '/img/dsmovie-Guerra_Mundial_Z.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Harry Potter e as Relíquias da Morte - Parte 1', '/img/dsmovie-Harry_Potter_e_as_Reliquias_da_Morte_-_Parte_1.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Harry Potter e a Pedra Filosofal', '/img/dsmovie-Harry_Potter_e_a_Pedra_Filosofal.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Alice no País das Maravilhas', '/img/dsmovie-Alice_no_Pais_das_Maravilhas.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Animais Fantásticos e Onde Habitam', '/img/dsmovie-Animais_Fantasticos_e_Onde_Habitam.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A Teoria de Tudo', '/img/dsmovie-A_Teoria_de_Tudo.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Livro de Boba Fett', '/img/dsmovie-O_Livro_de_Boba_Fett.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Último Duelo', '/img/dsmovie-O_Ultimo_Duelo.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Interestelar', '/img/dsmovie-Interestelar.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Contato', '/img/dsmovie-Contato.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Duna', '/img/dsmovie-Duna.webp');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Aquaman', '/img/dsmovie-Aquaman.webp');

INSERT INTO tb_score(movie_id, user_id, score_value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, score_value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, score_value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, score_value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, score_value) VALUES (2, 3, 4.0);
